# Generated by Django 3.0.5 on 2020-04-22 23:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('time_to_do', models.DateTimeField(default=datetime.datetime(2020, 4, 23, 23, 40, 15, 517530, tzinfo=utc))),
                ('Tasks_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.Username')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=100)),
                ('Username_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password', to='todo.Username')),
            ],
        ),
    ]
